import React from 'react';



const Banner = () => {
    return (
        <div 
    className="landing-page" 
    style={{
        accentColor: 'auto',
        placeContent: 'normal space-evenly',
        placeItems: 'center normal',
        placeSelf: 'auto',
        alignmentBaseline: 'auto',
        animationComposition: 'replace',
        animation: '0s ease 0s 1 normal none running none',
        appRegion: 'none',
        appearance: 'none',
        backdropFilter: 'none',
        backfaceVisibility: 'visible',
        background: 'none 0% 0% / auto repeat scroll padding-box border-box rgb(254, 239, 223)',
        backgroundBlendMode: 'normal',
        baselineShift: '0px',
        baselineSource: 'auto',
        blockSize: '611.333px',
        borderBlockEnd: '0px none rgb(33, 37, 41)',
        borderBlockStart: '0px none rgb(33, 37, 41)',
        borderColor: 'rgb(33, 37, 41)',
        borderRadius: '0px',
        borderStyle: 'none',
        borderWidth: '0px',
        borderCollapse: 'separate',
        borderEndEndRadius: '0px',
        borderEndStartRadius: '0px',
        borderImage: 'none 100% / 1 / 0 stretch',
        borderInlineEnd: '0px none rgb(33, 37, 41)',
        borderInlineStart: '0px none rgb(33, 37, 41)',
        borderStartEndRadius: '0px',
        borderStartStartRadius: '0px',
        inset: 'auto',
        boxShadow: 'none',
        boxSizing: 'border-box',
        breakAfter: 'auto',
        breakBefore: 'auto',
        breakInside: 'auto',
        bufferedRendering: 'auto',
        captionSide: 'top',
        caretColor: 'rgb(33, 37, 41)',
        clear: 'none',
        clip: 'auto',
        clipPath: 'none',
        clipRule: 'nonzero',
        color: 'rgb(33, 37, 41)',
        colorInterpolation: 'srgb',
        colorInterpolationFilters: 'linearrgb',
        colorRendering: 'auto',
        columns: 'auto',
        gap: 'normal',
        columnRule: '0px rgb(33, 37, 41)',
        columnSpan: 'none',
        containIntrinsicBlockSize: 'none',
        containIntrinsicSize: 'none',
        containIntrinsicInlineSize: 'none',
        container: 'none',
        content: 'normal',
        cursor: 'auto',
        cx: '0px',
        cy: '0px',
        d: 'none',
        direction: 'ltr',
        display: 'flex',
        dominantBaseline: 'auto',
        emptyCells: 'show',
        fill: 'rgb(0, 0, 0)',
        fillOpacity: 1,
        fillRule: 'nonzero',
        filter: 'none',
        flex: '0 1 auto',
        flexFlow: 'row',
        float: 'none',
        floodColor: 'rgb(0, 0, 0)',
        floodOpacity: 1,
        fontFamily: "'Bebas Neue', 'Bitter'",
        fontKerning: 'auto',
        fontOpticalSizing: 'auto',
        fontPalette: 'normal',
        fontSize: '16px',
        fontStretch: '100%',
        fontStyle: 'normal',
        fontSynthesis: 'weight style small-caps',
        fontVariant: 'normal',
        fontWeight: 400,
        grid: 'none',
        gridArea: 'auto',
        height: '22vh',
        hyphenateCharacter: 'auto',
        hyphenateLimitChars: 'auto',
        hyphens: 'manual',
        imageOrientation: 'from-image',
        imageRendering: 'auto',
        initialLetter: 'normal',
        inlineSize: '1258px',
        insetBlock: 'auto',
        insetInline: 'auto',
        isolation: 'auto',
        letterSpacing: 'normal',
        lightingColor: 'rgb(255, 255, 255)',
        lineBreak: 'auto',
        lineHeight: '24px',
        listStyle: 'outside none disc',
        marginBlock: '0px',
        margin: '0px',
        marginInline: '0px',
        marker: 'none',
        mask: 'none 0% 0% / auto repeat',
        maskType: 'luminance',
        mathDepth: 0,
        mathShift: 'normal',
        mathStyle: 'normal',
        maxBlockSize: 'none',
        maxHeight: 'none',
        maxInlineSize: 'none',
        maxWidth: 'none',
        minBlockSize: '0px',
        minHeight: '0px',
        minInlineSize: '0px',
        minWidth: '0px',
        mixBlendMode: 'normal',
        objectFit: 'fill',
        objectPosition: '50% 50%',
        objectViewBox: 'none',
        offset: 'normal',
        opacity: 1,
        order: 0,
        orphans: 2,
        outline: 'rgb(33, 37, 41) none 0px',
        outlineOffset: '0px',
        overflowAnchor: 'auto',
        overflowClipMargin: '0px',
        overflowWrap: 'normal',
        overflow: 'visible',
        overlay: 'none',
        overscrollBehaviorBlock: 'auto',
        overscrollBehaviorInline: 'auto',
        paddingBlock: '0px',
        padding: '0px',
        paddingInline: '0px',
        paintOrder: 'normal',
        perspective: 'none',
        perspectiveOrigin: '629px 305.667px',
        pointerEvents: 'auto',
        position: 'static',
        r: '0px',
        resize: 'none',
        rotate: 'none',
        rubyPosition: 'over',
        rx: 'auto',
        ry: 'auto',
        scale: 'none',
        scrollBehavior: 'auto',
        scrollMarginBlock: '0px',
        scrollMarginInline: '0px',
        scrollPaddingBlock: 'auto',
        scrollPaddingInline: 'auto',
        scrollTimeline: 'none',
        scrollbarGutter: 'auto',
        shapeImageThreshold: 0,
        shapeMargin: '0px',
        shapeOutside: 'none',
        shapeRendering: 'auto',
        speak: 'normal',
        stopColor: 'rgb(0, 0, 0)',
        stopOpacity: 1,
        stroke: 'none',
        strokeDasharray: 'none',
        strokeDashoffset: '0px',
        strokeLinecap: 'butt',
        strokeLinejoin: 'miter',
        strokeMiterlimit: 4,
        strokeOpacity: 1,
        strokeWidth: '1px',
        tabSize: 8,
        tableLayout: 'auto',
        textAlign: 'start',
        textAlignLast: 'auto',
        textAnchor: 'start',
        textDecoration: 'none solid rgb(33, 37, 41)',
        textDecorationSkipInk: 'auto',
        textEmphasis: 'none rgb(33, 37, 41)',
        textEmphasisPosition: 'over',
        textIndent: '0px',
        textOverflow: 'clip',
        textRendering: 'optimizelegibility',
        textShadow: 'none',
        textSizeAdjust: '100%',
        textTransform: 'none',
        textUnderlinePosition: 'auto',
        whiteSpace: 'normal',
        timelineScope: 'none',
        touchAction: 'auto',
        transform: 'none',
        transformOrigin: '629px 305.667px',
        transformStyle: 'flat',
        transition: 'all 0s ease 0s',
        translate: 'none',
        unicodeBidi: 'normal',
        userSelect: 'auto',
        vectorEffect: 'none',
        verticalAlign: 'baseline',
        viewTimeline: 'none',
        viewTransitionName: 'none',
        visibility: 'visible',
        widows: 2,
        width: '1258px',
        willChange: 'auto',
        wordBreak: 'normal',
        writingMode: 'horizontal-tb',
        x: '0px',
        y: '0px',
        zIndex: 'auto',
        zoom: '1'
    }}>
         <div className="wrapper" style = {{ display: 'flex',flexDirection: 'row',justifyContent: 'center',alignItems: 'center',width: '100%', height: '100%'}}>
         
         <svg className="red-line left-line">
        <line x1="100%" y1="50%" x2="0" y2="50%" stroke="#961717" strokeWidth="3" />
    </svg>

    <svg className="toledo-club" style={{opacity: "1"}}>
        <text style={{opacity: "1"}} x="75" y="85" className="toledo-club-text">Toledo Club</text>
    </svg>

    <svg className="squash-ball" style={{opacity: "1"}}>
        <circle cx="50" cy="50" r="50" fill="black" />
        <circle cx="55" cy="22" r="3.5" fill="yellow" className="dot-1" />
        <circle cx="63" cy="32" r="3.5" fill="yellow" className="dot-2" />
        <text style={{opacity: "1"}} x="7" y="57" className="squash-text">Squash.</text>
    </svg>

    <svg className="red-line right-line" style={{ marginLeft: '20px' }}>
        <line x1="100%" y1="50%" x2="0" y2="50%" stroke="#961717" strokeWidth="3" />
    </svg>
            
    


</div>
</div>

    );
};

export default Banner;




